apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugin-prometheus-pvc
  namespace: prometheus
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4T
  storageClassName: ""
  selector:
    matchLabels:
      pv: plugin-prometheus-pv