kind: Service
apiVersion: v1
metadata:
  name: devqa-devops-plugin-nginx-svc
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: nplb
    service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL"
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "true"
    service.beta.kubernetes.io/ncloud-load-balancer-name: "devqa-devops-plugin-nginx-svc"
    service.beta.kubernetes.io/ncloud-load-balancer-termination-protection: "true"
    service.beta.kubernetes.io/ncloud-load-balancer-ssl-certificate-no: "6225"
    service.beta.kubernetes.io/ncloud-load-balancer-tls-ports: "443"
    service.beta.kubernetes.io/ncloud-load-balancer-tls-min-version: "TLSV12"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: https
    port: 443
    targetPort: http