apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-devops-plugin-harbor-registry-pv
  labels:
    pv: dev-devops-plugin-harbor-registry-pv
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /n2589886_hlicomdevharbor/registry
    server: 169.254.0.19
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-devops-plugin-harbor-jobservice-pv
  labels:
    pv: dev-devops-plugin-harbor-jobservice-pv
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /n2589886_hlicomqaharbor/jobservice
    server: 169.254.0.19