apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-plugin-harbor-registry-pv
  labels:
    pv: devops-plugin-harbor-registry-pv
spec:
  capacity:
    storage: 2T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /n2589886_hlicommainharbor/registry
    server: 169.254.0.19
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-plugin-harbor-jobservice-pv
  labels:
    pv: devops-plugin-harbor-jobservice-pv
spec:
  capacity:
    storage: 2T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /n2589886_hlicommainharbor/jobservice
    server: 169.254.0.19