apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-plugin-harbor-registry-pvc
  namespace: harbor
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2T
  storageClassName: ""
  selector:
    matchLabels:
      pv: devops-plugin-harbor-registry-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-plugin-harbor-jobservice-pvc
  namespace: harbor
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2T
  storageClassName: ""
  selector:
    matchLabels:
      pv: devops-plugin-harbor-jobservice-pv