controller:
  kind: Deployment
  admissionWebhooks:
    enabled: false
  service:
    type: ClusterIP

  ingressClassByName: true
  ingressClassResource:
    name: dev-nginx-mci
  ingressClass: dev-nginx-mci
  
#  image:
    # Harbor에서 가져올 이미지
 #   registry: imgreg.heungkuklife.com
 #   image: nativeapp/nginx/ingress-nginx/controller
 #   tag: "v1.4.0"
 #   digest: ""

  replicaCount: 1

#  nodeSelector:
#    zone: coreapp

  # 자원 할당
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi

  config:
    ssl-redirect: "false"
    # 로그 (emerg > alert > crit > error > warn > notice > info > debug)
    error-log-level: "notice"
    # 로그 포맷
    log-format-upstream: '[$time_local] [$host]$remote_addr - [$hostname]$server_addr Sta[$status] Dur[$request_time] - [$service_name][pod]$upstream_addr $request $content_type Sta[$upstream_status] Dur[$upstream_response_time] ReqLen[$request_length] ResLen[$upstream_response_length]'
    # Pod의 Response 평균치를 기준으로 부하 분산
    load-balance: "ewma"
    # 사이즈 제한 (Com 업무단 협의사항)
    proxy-body-size: 50m
    # 트래픽 제한 (mci,fa 업무단 협의사항)
    proxy-read-timeout: "600"
 #   proxy-connect-timeout: "600"
    proxy-send-timeout: "600"
    # a client request body is buffered to a temporary file 발생시 설정
    client-body-buffer-size: "1m"  # Default 8k

  # Log Write 타임존 설정
  extraEnvs:
    - name: TZ
      value: Asia/Seoul

  service:
    enabled: false