controller:
  kind: Deployment
  admissionWebhooks:
    enabled: false
  service:
    type: ClusterIP
  image:
    digest: ""

  replicaCount: 2

  # 자원 할당
  resources:
    limits:
      cpu: 1
      memory: 8Gi
    requests:
      cpu: 1
      memory: 8Gi

  config:
    #로그레벨
    error-log-level: "notice"

    # a client request body is buffered to a temporary file 발생시 설정
    client-body-buffer-size: "1m"  # Default 8k

  # Log Write 타임존 설정
  extraEnvs:
    - name: TZ
      value: Asia/Seoul

# 자체 PSP사용
podSecurityPolicy:
  enabled: true