# Cassandra 설정
image:
  # 로그레벨
  debug: false

# 자원 할당
resources:
  limits:
    cpu: 2
    memory: 16Gi
  requests:
    cpu: 2
    memory: 16Gi

# NKS BlockStorage를 사용하기 위한 StorageClass 설정
persistence:
  enabled: true
  storageClass: "devops-plugin-sc"
  accessModes:
    - ReadWriteOnce
  size: 500Gi

# loki에서 접속을 하기 위한 계정 생성
dbUser:
  user: loki
  password: hlico123#